name: api deploy

on:
  push:
    branches:
      - feat/#1
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kotlin-version: [ "1.9.23" ]
        java-version: [ "17" ]

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          kotlin-version: ${{ matrix.kotlin-version }}
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create config file
        run: |
          mkdir -p ./core/src/main/resources
          echo "${{ secrets.APPLICATION_CORE_YML }}" > ./core/src/main/resources/application-core.yml

      - name: Build with Gradle
        run: ./gradlew :api:build --no-daemon

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker image build
        run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/boai:server .

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/boai:server

      - name: Deploy with push
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_PAIR }}
          port: ${{ secrets.PORT }}
          script: |
            docker -v
            sudo docker stop boai-server || true
            sudo docker container prune -f
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/boai:server
            docker images
            sudo docker run -d --log-driver=syslog \
            -e TZ=Asia/Seoul \
            -p 8080:8080 --name boai-server \
            ${{ secrets.DOCKERHUB_USERNAME }}/boai:server